version: '3.8'
services:
  cover-letter-frontend:
    container_name: reedai_client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
