import { REEDAI_PROMPTS_LIBRARY } from '@/config/ai';

export const ReedAiLib = {
  meta: {
    system: REEDAI_PROMPTS_LIBRARY.GENERATE_AI_SYSTEM_PROMPT,
    assistant: REEDAI_PROMPTS_LIBRARY.GENERATE_AI_ASSISTANT_PROMPT,
    tools: REEDAI_PROMPTS_LIBRARY.GENERATE_AI_TOOL_PROMPT,
    user: REEDAI_PROMPTS_LIBRARY.GENERATE_AI_USER_PROMPT_ENHANCEMENT,
  },
  generative: {
    pineconeAssistant: REEDAI_PROMPTS_LIBRARY.PINECONE_CONTEXT_ASSISTANT,
    componentGen: REEDAI_PROMPTS_LIBRARY.OPENAI_COMPONENT_CREATOR,
    clineArtifacts: REEDAI_PROMPTS_LIBRARY.CLINE_ARTIFACTS_CREATOR,
    openArtifacts: REEDAI_PROMPTS_LIBRARY.OPEN_ARTIFACTS_CREATOR,
  },
};

export default ReedAiLib;
